### PR TITLE
Print examples using definition example fields

### PR DESCRIPTION
**Pull request by mikejholly**
Handy dandy examples generated (recursively) from Swagger source file examples.

bucket-result

@auscaster

### CODE REVIEW

**Comment by auscaster** [comment]
Legend, thanks for this :+1:

**Comment by marcelgwerder** [comment]
Hi

For me this PR breaks most of the examples. 

Addaptions to the code change missing (there might be more):

- [`{{printSchema example}}`](https://github.com/sourcey/spectacle/blob/8a9705faaeaddd5f475e71a6497ec1a3e4aa002c/app/views/partials/json-schema/body.hbs#L14) should be  `{{printSchema .}}`
- [`{{>swagger/print-schema example}}`](https://github.com/sourcey/spectacle/blob/8a9705faaeaddd5f475e71a6497ec1a3e4aa002c/app/views/partials/swagger/definition.hbs#L52) should be `{{>swagger/print-schema .}}`

Wrong check/params break array output.
https://github.com/sourcey/spectacle/blob/8a9705faaeaddd5f475e71a6497ec1a3e4aa002c/app/lib/common.js#L77
The above should probably be:
 ```js
//...
else if (value.schema && value.schema.items && value.schema.items.$ref) {
	  return this.formatExampleProp(value.schema.items, root);
}
//...
```

With those changes I got it to show the examples again. But they are without the feature added by this PR. Didn't have time to have a look at this as well.

I didn't spend a lot of time in the code so I can't be 100% sure that I understood it correctly.
I'll revert back to 0.7.0 for now.

regards,
Marcel

**Comment by auscaster** [comment]
@marcelgwerder can you please provide a snippet of your swagger file, or how you define examples and I'll take a look today.

**Comment by auscaster** [comment]
@mikejholly would you be able to provide a snippet of your swagger file too please? Looks like this one is breaking things for some people

**Comment by auscaster** [comment]
Reverting temporarily until issues can be solved ... although I haven't tested it myself yet fully the code in question does look a bit iffy

**Pull request merged**
