### PR TITLE
Bugfix: wrong return type

### PR DESCRIPTION
**Pull request by CodeLenny**
Missed an error in #31.  See #30.

### CODE REVIEW

**Comment by auscaster** [comment]
OK thanks for the quick patch 👍

**Comment by CodeLenny** [comment]
Yep, glad it was so easy!

**Comment by CodeLenny** [comment]
@auscaster Looks like it passes tests this time.  Could we get a version bump?

Thanks again!

**Comment by auscaster** [comment]
Done :)

**Comment by CodeLenny** [comment]
Thanks!

**Pull request merged**
