### PR TITLE
Added support for referencing remote schemas

### PR DESCRIPTION
**Pull request by CodeLenny**
Hi @auscaster,

I've been exploring support for referencing remote files.  I've managed to hack support in, but it's very ugly.

Given that you're more familiar with the code base, I wondered if you'd have an opinion of the cleanest way to get the data needed to read remote files.

It looks like the only things that `common.resolveSchemaReference` needs is a path to the current file (to resolve relative references) and `options` to pass along to `/lib/preprocessor`.

- ~~Clean relative references~~
- ~~Clean passing `options` for `preprocessor`.~~

I haven't tested deep file references, but OpenAPI's [petstore-seperate](https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v2.0/yaml/petstore-separate) is working for me (although I did flatten the file paths, and should test on the original).

screenshot from 2017-03-02 19-48-36

- [x] Build doesn't error out when a remote file is referenced
- [x] Response examples from remote files are included

---

*Task list has been re-organized since the first message in this PR.  The below list is the current state of the PR.  Please note that many changes were directly implemented, and never added to the list.*

- Tests
  - [x] Test complex paths
  - [x] Test deep file references
  - [x] Test files requested over HTTP
  - [x] Test "contexts"
  - [ ] Add failure-case tests (`replaceReference`, `replaceRefs`)
  - [x] Document testing in `README`
  - [x] Add remote reference inside `cheesestore.json`

- Remote Schema Evaluation
  - [x] Remote URLs could be cached to provide better performance (if not desired, remove `TODO` comment on `fetchReference`)
  - [x] Relative URLs don't work with Remote URLs
  - [x] Local paths in external files aren't handled (see `replaceRefs`)
  - "reference contexts" (utilities that recognize `"/responses/[code]/schema"` as something to insert into `"/definitions/[...]"`
    - ~~Add additional contexts~~ (2nd PR)
    - ~~Make contexts optional~~ (2nd PR)

- Tags
  - [x] Handle tags as needed

- UI
  - ~~Tweak names to remove paths?  (in definitions, `Pet.yml` -> `Pet`, `defs.yml#/things/Pet` -> `Pet`)~~ (2nd PR)
  - ~~Add "Imported From"~~ (2nd PR)
  - ~~Add tests?~~
  - [x] Schema definitions aren't copied into the main page

Random issues noted that should be checked at the end:
- [ ] Parameter definitions aren't working
- [ ] Path ordering is done before paths in external references have been added

### CODE REVIEW

**Comment by auscaster** [comment]
Hey there :)

I will be great to get this feature into spectacle, thanks a lot for your work!

As you say there are a few things to consider before we merge this into the core, but you seem to have a solid handle on them.

I wonder, however, if it wouldn't be cleaner to to load remote references on the first call to the [processor](https://github.com/CodeLenny/spectacle/blob/e5e46227360f55e6a7845fefc21ed0484edf9118/app/lib/preprocessor.js#L9), so we can keep that logic out of the view helpers.

**Comment by CodeLenny** [comment]
@auscaster Glad to have your support.

Moving this into the processor sounds much better.  Would you be able to point me to where the reference loading would fit in nicely?  It looks like the existing code might not iterate over keys deep enough to find all references, but I haven't explored the preprocessor in depth yet.

**Comment by auscaster** [comment]
True there is no code that does that in the preprocessor. 

The easiest way would be to use recursion, something like this:

```
// Feed the JSON object into a function like this
function eachRecursive(obj) {
    for (var k in obj) {
        if (typeof obj[k] === "object" && obj[k] !== null)
            eachRecursive(obj[k]); // check next level
        else
            // chech `obj[k]` for external references that need to be resolved and do work, or continue... 
    }
}
```

**Comment by CodeLenny** [comment]
@auscaster Glad I read it correctly!  Should I add the recursive loop to load references before [looping over the methods](https://github.com/CodeLenny/spectacle/blob/e5e46227360f55e6a7845fefc21ed0484edf9118/app/lib/preprocessor.js#L25) or would it fit somewhere else?

**Comment by auscaster** [comment]
At the end of the preprocessor would be best.

**Comment by CodeLenny** [comment]
@auscaster Will do.

Another question: Should imported definitions/parameters/responses be added to the global objects?

For instance, should the following files:

```yaml
# petshop-seperate.yaml
swagger: "2.0"
paths:
  /pets:
    get:
      description: Get all the pets.
      responses:
        "200":
          schema:
              type: array
              items:
                $ref: 'Pet.yaml'
```

```yaml
# Pet.yaml
type: object
required:
  - id
  - name
properties:
  id:
    type: integer
    format: int64
```

Be equivalent to:

```yaml
# petshop-unitifed.yaml
swagger: "2.0"
paths:
  /pets:
    get:
      description: Get all the pets.
      responses:
        "200":
          schema:
              type: array
              items:
                $ref: '#/definitions/Pet'
definitions:
  Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
```

Meaning the Pet object definition would be included in the docs with all other definitions?

I could see deep definitions providing an additional hurdle, and either way, the URL re-writer would have to be re-implemented (it currently does "#/definition/" -> "#definition-")

**Comment by auscaster** [comment]
Hey there, nice to see you made some progress! Yes I think we need to merge the referenced objects into the root spec, and make the definitions available or the resulting document will have broken links.

**Comment by CodeLenny** [comment]
@auscaster Glad to hear you agree.  Shall I just insert definitions into the original YAML/JSON document, or do you want a fancier method?

When I'm merging, I'm guessing I can use some relative path to the file to keep references seperate:

```yaml
definitions:
  # From the primary document
  Pet: ...
  # From an external document
  "../defs/Pet": ...
```

Or do you have a cleaner way to put the name?

Thanks again!

**Comment by auscaster** [comment]
Hmmmm .... I think be can just merge them into the main document, but maybe we add a custom internal `_external` attribute (underscore to flag internal) and assign it with the external file name or URL. ie.

~~~
definitions:
  # From the primary document
  Pet: ...
  # From an external document
  Pet:
    _external: <external filename or URL>
~~~

Then when we generate the documentation we can render the `_external` a field below the description with some text like "Imported from <external filename or link>"

What do you think?

**Comment by CodeLenny** [comment]
@auscaster And I guess if the reference isn't to a specific object in a file, we should use the filename as the entry in the definitions section?

If someone linked to `defs.yaml#/jobs/Programmer`, we can easily create:

```yaml
definitions:
  Programmer:
    _external: "defs.yaml#/jobs/Programmer"
```

And if someone linked to `jobs/Architect.yaml`, we use:

```yaml
definitions:
  Architect:
    _external: "jobs/Architect.yaml"
```

An alternative is to provide the entire path in the key.  This would fix problems if two documents used the same definition name, like "Error".

```yaml
definitions:
  "../users/defs/Error": {}
  "../items/defs/Error": {}
```

Which would also give us unique paths in URLs: `index.html#../items/defs/Error`.  When creating the human readable presentation, it could simplify the section title down to just "Error", and provide the full field underneath, with "Imported from".

I've found other documentation systems like [codo](https://github.com/coffeedoc/codo) only create URLs based on class name, when I might want to use the same class name in different files, which has caused some problems.  If there might be similar use cases (like generic names, `Error`, `Options`, `Data`), it would be nice to have a plan taking them into account.

**Comment by auscaster** [comment]
I like your approach using keys, and you are right it was prevent
collisions and make linking easier :)

**Comment by CodeLenny** [comment]
@auscaster Great!

I'm breaking the program down into some simpler functions, and would like to write some tests, both to ensure the program functions as desired, but also to formalize the functionality that I'm adding.

Could I include some tests in the repository?  I generally write tests with Mocha and Chai, but I can use another system if desired.

Thanks!

**Comment by auscaster** [comment]
That would be awesome .... please go ahead and add some proper testing
with Mocha
and Chai! The current system really needs it :+1

**Comment by CodeLenny** [comment]
@auscaster Cool, I've already started.  I assume I can export some of the new functions I'm adding to `preprocessor`, and change `npm test` to run Mocha?  Then it can be integrated with Travis CI or a similar test runner.

**Comment by auscaster** [comment]
Nice :)

Have you used circleci before? I use it for all my projects and its great.

**Comment by CodeLenny** [comment]
@auscaster I haven't, so I'd probably let you set it up.

**Comment by CodeLenny** [comment]
@auscaster I've added a first testing file.  Do you want to see if my testing style (Mocha + Chai 'should' syntax) matches yours enough?  It would be relatively simple to change it at this stage, before I write a lot more tests.

**Comment by auscaster** [comment]
Your test syntax is great, and even better, tests are passing!

Please go ahead with what you are doing :)

**Comment by CodeLenny** [comment]
Glad to hear it!

I've been thinking more about how to structure the loops in the preprocessor.

According to the OpenAPI spec, references can only be used in a few specific places.  For the most part, we want to simply replace the reference line with the contents of the remote file.  However, there are a few cases where we want to do additional actions (such as inserting the remote contents into the definitions section, and replacing the external reference with a local reference).

I can see two approaches:

**1.** We search out the few places the spec allows references, and only evaluate those.  For instance, we assume that there's a `paths` object containing objects for each path.  We only go into `paths`, and ignore other sections and fields like `info`.

**Pros**
- Almost certainly more efficient
- Provides a more spec-driven behavior, with fewer side-effects

**Cons**
- Must write custom code for each `$ref` "scenario" (and might miss some)
- Must be kept revised when spec changes

**2.** We do the previously proposed global search, walking the entire tree to find any usage of `$ref` that links to an external source, and replace the object with the remote contents.  If we recognize the current path as one of the special cases (like definitions to move elsewhere in the local document) we can apply special processing.

**Pros**
- Allows flexibility in use cases (some users might want to have `info` in a different document)

**Cons**
- "Recognizing" the current path isn't as pretty

--- 

@auscaster I'm not sure which is better.  I'm leaning towards option 2, but I'd be interested in hearing what you think.

**Comment by auscaster** [comment]
@CodeLenny if we can probably reduce code complexity at a negligible performance hit and get the desired result then let's do it, #2 seems like the simpler approach

**Comment by auscaster** [comment]
By the way I just wanted to say thanks for the effort you're putting into spectacle :+1: 

I'll create a contributors section on the README soon and would very much like to add you.

**Comment by CodeLenny** [comment]
@auscaster I've started approach 2.

I'm happy to help, we're using the software at my office, and wanted to add this feature for our own use.

I'm trying to find where you parse YAML files.  It appears that `loadData` in `index.js` just [calls `require()`](https://github.com/sourcey/spectacle/blob/master/index.js#L52) on whatever spec file is given:

```js
return require(path.resolve(opts.appDir + '/lib/preprocessor'))(
                                    options, require(specPath));
```

I didn't think that `require` could deal with YAML files, but I might be mistaken.  Is there something I'm missing?

Thanks!

**Comment by CodeLenny** [comment]
@auscaster Any ideas about how YAML files are parsed?  I've been studying all the code, and can't figure it out.

Thanks!

**Comment by auscaster** [comment]
YAML needs an external library, nodejs's `require` just parses JSON I
believe.

Check here:
http://thisdavej.com/getting-started-with-yaml-in-node-js-using-js-yaml/

https://www.npmjs.com/package/js-yaml looks like the best bet.

I guess we will need a loadFile helper if you want to load either, and
check the file extensions to selectively parse the file.

**Comment by auscaster** [comment]
Hmmm I could be mistaken .... don't take my word for it )

**Comment by CodeLenny** [comment]
@auscaster Glad to know I wasn't missing something in the source code.  I'll just throw `js-yaml` when I'm reading referenced YAML files.

**Comment by CodeLenny** [comment]
@auscaster I just realized I've set my file line length to 120 characters, and I think you're using 80 everywhere else.  Shall I change the code I've written to meet your style?  You might want to add a lint specification to enforce a standard in the future.

**Comment by auscaster** [comment]
You make me feel very guilty with your nice clean & commented code 💛

**Comment by auscaster** [comment]
Regarding line length I'm personally OK with 120 chars since I think most people have large monitors these days. Nice idea regarding linter also, I'll add it to the TODO

**Comment by CodeLenny** [comment]
@auscaster Cool, good to know.  I've been putting lint in my CI systems, which has worked pretty well.

**Comment by CodeLenny** [comment]
@auscaster I'd like to create some custom error types to use when parsing.  Should I create `/app/lib/errors.js` to have a single location for all new error types?

**Comment by auscaster** [comment]
Sounds good 👍

**Comment by CodeLenny** [comment]
@auscaster I'm adding quite a bit of heavy lifting to the pre-processor, especially if I'm reading remote resources.  I'm currently using synchronous methods as the rest of the preprocessor is synchronous, but I'm guessing it would be more efficient if these additions could take advantage of Node's async support.

Shall I continue with synchronous methods as I have been, or should the preprocessor support asynchronous methods?

**Comment by CodeLenny** [comment]
@auscaster I think I've gotten most of the assisting functions ready to be used - just have to put the final touches on them and wire them into the preprocessor.

This seems to be a nice checkpoint, would you care to skim through the code written so far before I continue much farther?

Thanks!

**Comment by auscaster** [comment]
I've done a review of your code and it looks perfect - full credit to you! Most/all of the new functionality is isolated too so I highly doubt it will adversely affect the existing system in any way.

Regarding async vs sync there is not much point since we will need to wait for any file/web requests to complete before rendering anyway. The best we can do is sync and cache.

Power on!!

**Comment by auscaster** [comment]
Just on a professional note, are you currently available for work? If so shoot me a message, I have an exciting opportunity: auscaster@gmail.com

**Comment by CodeLenny** [comment]
@auscaster Thanks for the feedback!  I'll get cracking on the last bits.

Async would still help parallize the tasks - I'm having to do a bit of file read/web requests to get the contents of requested spec files, which could be fetched in the background while other parts of the spec are processed.  I even had to grab the `request-sync` package, as the normal `request` package doesn't allow synchronous HTTP requests.  However, it probably doesn't make sense to switch over at this point.

**Comment by CodeLenny** [comment]
@auscaster Status update!

I've got my functions integrated into the preprocessor, and started "context matching", which recognize known paths like "responses/[code]/schema" as being things to insert into "definitions" instead of including multiple times in the document.

Initial testing looks good!  I did notice that the sidebar is out of order, as the ordering occurs before references are looked up.  It doesn't look like I broke much else of the UI, although extensive testing is definitely called for.

screenshot from 2017-03-17 12-28-04

I've got a couple known items to still resolve, such as testing some edge cases that I know haven't been looked at.

I might push some of the extra features to be done a second PR, including the comprehensive set of "context matchers" to get things merged quicker.  I've updated the task list at the top of this MR with `(2nd PR?)` with items I think can be skipped for this round.  I'm near the end of time I can devote to sprinting on this task, so I'd love to wrap it up in a couple of days and focus on a few other things.

**Comment by auscaster** [comment]
Awesome work! 

My first thought when seeing the .yaml prefix in the Model name is that it wont make sense for the documentation viewer, who only cares about the API logic. Maybe below the definition title we should add a link or or at least the name of the source document for external sources. What do you think?

**Comment by CodeLenny** [comment]
@auscaster I already updated the [PR Summary](https://github.com/sourcey/spectacle/pull/41#issue-211565074) to include those items as tasks:

- Tweak names to remove paths? (in definitions, Pet.yml -> Pet, defs.yml#/things/Pet -> Pet) (2nd PR?)
- Add "Imported From" (2nd PR?)

As I haven't touched the UI side of the code yet in this PR, I'd be interested in seeing if things work "well enough" as is for this PR, and leave the full UI tweaks for later.

However, it would be nice to have a few tests to ensure that at least the current functionality (with `.yaml`) continues working.

**Comment by auscaster** [comment]
👍

**Comment by CodeLenny** [comment]
@auscaster I've polished a few more parts of the code.

1) I've updated the `README` with a brief explanation about testing methodology.
  Please let me know if you have any suggestions for the text.

2) Paths are being inserted out of order.  I wasn't able to figure out what part of the code reorders the paths.  
Would you be able to easily point out where ordering is taken into account, or should I dig deeper?

3) I'm a little uncomfortable about merging this without adding any tests confirming that the outputted UI is acceptable, but I'm unfamiliar with your UI code, and it seems a lot to dig into just to add a little testing.  
Would you be all right if we moved forward with the PR without touching the UI, if the output looks acceptable?

4) Have I missed anything in my [PR Summary](https://github.com/sourcey/spectacle/pull/41#issue-211565074) that should be added to this PR?

I've still got a few last changes to finish, but it looks like this PR is getting close to being done.

Thanks as always!

**Comment by auscaster** [comment]
Hello

Everything looks to be in order - except paths ;) Regarding that paths are currently ordered by Tags, which allows for the tab based categorization in the sidebar [template here](https://github.com/sourcey/spectacle/blob/master/app/views/partials/swagger/tags.hbs). It calls the `eachSorted` method which may need to be refactored to get paths displaying in the desired order. Is that something you need?

As long as we can get the output looking good I am happy. What I might do is add some remote swagger items to `cheesestore.json` just so at least the UI code gets touched on each call to `npm test`, and the remote swagger markup will be visible on the live demo.

**Comment by CodeLenny** [comment]
@auscaster Ah yes, I completely ignored tags.  I'll take a look at implementing that when I add paths from external files.

I'll look at adding remote items to `cheesestore.json`.

**Comment by CodeLenny** [comment]
@auscaster Any chance Circle CI could be linked with GitHub so PRs are tested, and the result is displayed in the GitHub UI?  Would make me more comfortable :)

**Comment by auscaster** [comment]
Hi there, sorry for the slow response. Hardly surprising though since my company commitments have really ramped up lately!

I've added CircleCI to pull requests .... hopefully it will work for existing PRs?

Hows it all coming together on your end?

**Comment by CodeLenny** [comment]
Hey @auscaster, it's been busy here as well, but I should have some free time now to work on the PR again.

It looks like CircleCI didn't run tests on this PR.  It might be complaining that this PR is from my own branch - I know Travis detects this and blocks external CIs from seeing private variables, as I might adjust the CI config to `echo $SECRET_PASSWORD` or something.  Would it be possible to look into this more?

Looks like I mainly just need to deal with tags, and might write additional unit tests to check a few edge cases, but it looks like this PR is wrapping up, with most of the "fancy" features pushed to another PR.

**Comment by CodeLenny** [comment]
@auscaster I've also been using [JSVerify](https://github.com/jsverify/jsverify) for testing in some of my other projects.  It attempts to find counter-cases when given a property to prove - it only checks random input instead of truly proving the algorithm, but I've found it to be much simpler than building a library of test cases.

I'm not able to spend the time integrating it for this PR, but it's something to consider for later PRs.

**Comment by auscaster** [comment]
Hey there, just checking in here! I'm sure you've moved on to other things but I would love to see your work merged into master. Is there anything that we need to address before that happens?

**Comment by CodeLenny** [comment]
@auscaster 

- The code currently ignores tags as I only used examples without tags.
- The PR lacks CircleCI testing
- Code hasn't been reviewed, if you wanted to

Not too much left!

**Comment by auscaster** [comment]
I had a go at getting Circle working for your PR but no luck. If you create
a branch of `sourcey/spectacle` and merge the PR into that I think it will
work.

Regarding tags, they are actually quite important. Paths are combined
categorically using tags (you can see it on the demo). If we can maintain
that functionality it would be great.

Other than that the code looks great and I would be happy to merge it in.

Have you been able to implement spectacle successfully for your company yet?

**Comment by auscaster** [comment]
Merging this in. Hope you are well and your projects are coming along nicely Lenny!

**Comment by CodeLenny** [comment]
@auscaster Sorry I didn't finish it fully, it's been quite a bit crazy here.  Thanks for merging!

**Pull request merged**
